#!/bin/bash
REPO="https://github.com/FasterExE/VIP-OvpnLS/raw/main"
apt install jq curl -y
rm -rf /etc/xray/domain
rm -rf /etc/xray/flare-domain
mkdir -p /root/xray
clear
sub=$(</dev/urandom tr -dc a-z0-9 | head -c5)
DOMAIN=ilyass.my.id
WS_DOMAIN=ws-${sub}.ilyass.my.id
FLARE_DOMAIN=flare-${sub}.ilyass.my.id
NS_DOMAIN=ns-${sub}.ilyass.my.id
CF_ID=ilyassnajhi10@gmail.com
CF_KEY=c802b86ce41793d4aed457ad769889b7e31e9
set -euo pipefail
IP=$(curl -sS ifconfig.me);
echo "Updating DNS for ${WS_DOMAIN}..."
ZONE=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones?name=${DOMAIN}&status=active" \
-H "X-Auth-Email: ${CF_ID}" \
-H "X-Auth-Key: ${CF_KEY}" \
-H "Content-Type: application/json" | jq -r .result[0].id)
RECORD=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${WS_DOMAIN}" \
-H "X-Auth-Email: ${CF_ID}" \
-H "X-Auth-Key: ${CF_KEY}" \
-H "Content-Type: application/json" | jq -r .result[0].id)
if [[ "${#RECORD}" -le 10 ]]; then
#start-ws
RECORD=$(curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
-H "X-Auth-Email: ${CF_ID}" \
-H "X-Auth-Key: ${CF_KEY}" \
-H "Content-Type: application/json" \
--data '{"type":"A","name":"'${WS_DOMAIN}'","content":"'${IP}'","ttl":120,"proxied":false}' | jq -r .result.id)
fi
#end-ws
echo "Updating DNS FLARE for ${FLARE_DOMAIN}..."
#start-flare
RECORD=$(curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
-H "X-Auth-Email: ${CF_ID}" \
-H "X-Auth-Key: ${CF_KEY}" \
-H "Content-Type: application/json" \
--data '{"type":"CNAME","name":"'${FLARE_DOMAIN}'","content":"'${WS_DOMAIN}'","ttl":120,"proxied":true}' | jq -r .result.id)
#end-flare

echo $WS_DOMAIN >/etc/xray/domain
echo $FLARE_DOMAIN >/etc/xray/flare-domain
echo $NS_DOMAIN >/etc/xray/dns
cd
rm -rf cf
sleep 1
}

setup_dnstt() {
    cd
    rm -rf *
    mkdir -p /etc/slowdns
    wget -O dnstt-server "${REPO}slowdns/dnstt-server" && chmod +x dnstt-server >/dev/null 2>&1
    wget -O dnstt-client "${REPO}slowdns/dnstt-client" && chmod +x dnstt-client >/dev/null 2>&1
    ./dnstt-server -gen-key -privkey-file server.key -pubkey-file server.pub
    chmod +x *
    mv * /etc/slowdns
    wget -O /etc/systemd/system/client.service "${REPO}slowdns/client" >/dev/null 2>&1
    wget -O /etc/systemd/system/server.service "${REPO}slowdns/server" >/dev/null 2>&1
    sed -i "s/xxxx/$NS_DOMAIN/g" /etc/systemd/system/client.service
    sed -i "s/xxxx/$NS_DOMAIN/g" /etc/systemd/system/server.service
}
ns_domain_cloudflare
setup_dnstt
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
iptables-save >/etc/iptables/rules.v4 >/dev/null 2>&1
iptables-save >/etc/iptables.up.rules >/dev/null 2>&1
netfilter-persistent save >/dev/null 2>&1
netfilter-persistent reload >/dev/null 2>&1
systemctl enable iptables >/dev/null 2>&1
systemctl start iptables >/dev/null 2>&1
systemctl restart iptables >/dev/null 2>&1
